# Model parameters
EMBEDDING_DIM = 50
HIDDEN_SIZE = 50
NUM_LAYERS = 5
NUM_EPOCHS = 10
LEARNING_RATE = 0.001
BATCH_SIZE = 5
DROPOUT = 0.4
PAD = 1
LABELS_SIZE = 24
ENTITIES_LABELS_SIZE = 19
INTENTS_LABELS_SIZE = 7

label_map = {
    'NONE': 0,
    'BPIZZAORDER': 1, 'IPIZZAORDER': 2,
    'BDRINKORDER': 3, 'IDRINKORDER': 4,
    'BCOMPLEX_TOPPING': 5, 'ICOMPLEX_TOPPING': 6,
    'BNUMBER': 7, 'INUMBER': 8,
    'BSIZE': 9, 'ISIZE': 10,
    'BVOLUME': 11, 'IVOLUME': 12,
    'BCONTAINERTYPE': 13, 'ICONTAINERTYPE': 14,
    'BDRINKTYPE': 15, 'IDRINKTYPE': 16,
    'BSTYLE': 17, 'ISTYLE': 18,
    'BQUANTITY': 19, 'IQUANTITY': 20,
    'BTOPPING': 21, 'ITOPPING': 22, 
    'NOT': 23
}
entities_label_map = {
    'NONE': 0,
    'BNUMBER': 1, 'INUMBER': 2,
    'BSIZE': 3, 'ISIZE': 4,
    'BVOLUME': 5, 'IVOLUME': 6,
    'BCONTAINERTYPE': 7, 'ICONTAINERTYPE': 8,
    'BDRINKTYPE': 9, 'IDRINKTYPE': 10,
    'BSTYLE': 11, 'ISTYLE': 12,
    'STYLE_NOT': 13,
    'BQUANTITY': 14, 'IQUANTITY': 15,
    'BTOPPING': 16, 'ITOPPING': 17, 
    'TOPPING_NOT': 18
}
intents_label_map = {
    'NONE': 0,
    'BPIZZAORDER': 1, 'IPIZZAORDER': 2,
    'BDRINKORDER': 3, 'IDRINKORDER': 4,
    'BCOMPLEX_TOPPING': 5, 'ICOMPLEX_TOPPING': 6,
}